code sdr
marsiitr/Sand-Drawing-Robot pull request #1
Opened 2020-07-24 14:08 UTC by ravinab29

code of sand drawing robot

2020-07-24 15:10 UTC, SanjeevKrishnan requested changes
@ravinab29 
All the required files have to be uploaded as mentioned in the documentation guideline.
1. Refer guideline and upload Images, Videos, Solidworks files, Report, Poster in respective folders.
2. Python/Arduino codes have to be inside the src folder.
3. Maintain general terminology to name your files to make it comprehensible by all kinds of audiences. 
4. README.md file is empty. Refer guideline and update it accordingly.

2020-07-28 13:54 UTC, Shubhanshu07 commented on README.md
> + ![image](C:\Users\hp\Documents\sdr.jpg)
Image is not rendering.

2020-07-28 13:55 UTC, Shubhanshu07 commented on README.md
> +
Should be in ordered list

2020-07-28 14:00 UTC, Shubhanshu07 commented
@ravinab29 
1. Mechanical Design Folder is missing.
2.  Poster and Report, Images and Videos folder are not there.
3.  Readme is not upto the  mark.
4. Flow chart is missing.

2020-07-28 16:36 UTC, ravinab29 commented
sir i have updated the readme part. kindly review it.

2020-07-28 20:06 UTC, SanjeevKrishnan commented
> @ravinab29
> 
> 1. Mechanical Design Folder is missing.
> 2. Poster and Report, Images and Videos folder are not there.
> 3. Readme is not upto the  mark.
> 4. Flow chart is missing.

@ravinab29  Still these changes are not updated. Also, tag us when all the changes are done. Reviewing individual files is not feasible.

2020-07-29 09:38 UTC, SanjeevKrishnan requested changes
@ravinab29 Changes are still required!
1. Videos is missing. Try to have at least one video as it will be advantageous to your repo. You can try making a screen recorded video of Arduino stimulation.
2. Rename "images" as "Images"
3. Mechanical Design folder is missing.
4. Justify the text in Report.
5. File names are not proper. Names should be self-explanatory.
6. In README.md, justify text using `<p align="justify">Content<\p>` where content is the text you want to justify.

2020-07-29 09:38 UTC, SanjeevKrishnan commented on README.md
> +User gives an image, python code converts image to pixelated image such that only two pixel values will be stored for the image ,one stepper motor moves the shaft vertically with the given time gap a
Flowchart is missing

2020-07-29 09:38 UTC, SanjeevKrishnan commented on README.md
> +**Beaches** - on sand we can draw one’s picture.
Applications, Limitations, and Future improvements have to be unordered list.

2020-07-29 09:38 UTC, SanjeevKrishnan commented on README.md
> + [Sejal Agarwal](https://github.com/sejal-ag)
Team Members and Mentors names should be in ordered list.

2020-07-29 11:10 UTC, Shubhanshu07 commented
@ravinab29 
1. I should be capital in Images folde

2020-07-29 12:10 UTC, Shubhanshu07 commented
@ravinab29  Nice work. PR looks good to me.

2020-07-29 12:11 UTC, merged